config/routes.rb
Rails.application.routes.draw do

  root 'todos#index'
  get 'todos', to: 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'todo_edit'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as: 'todo_completed'
  get 'list', to: 'todos#list', as: 'todo_list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    @todo.save
      redirect_to todos_path

  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)

    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.delete

    redirect_to todos_path
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save

    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end

  private
  def todo_params
    params.require(:todo).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

     <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
       <div class="navbar-nav">
         <a class="nav-item nav-link active" href="<%= todos_path %>">Inicio <span class="sr-only">(current)</span></a>
         <a class="nav-item nav-link" href="<%= todo_list_path %>">lista</a>
         <a class="nav-item nav-link" href="<%= todos_new_path %>">formulario</a>
       </div>
     </div>
   </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <%= yield %>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f| %>
  <div class="form-group">
    <%= f.label :description, 'Descripcion' %>
    <%= f.text_field :description, class: 'form-control', placeholder: 'ejemplo'%>
  </div>

  <%= f.submit "Guardar tarea", class: 'btn btn-primary' %>
<% end %>

app/views/todos/edit.html.erb
<%= render 'layouts/navbar' %>

<!-- boton para volver -->
<%= link_to "volver", todos_path, class: 'btn btn-success float-right' %>

<h1>edit ToDo</h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<%= render 'layouts/navbar' %>

<!-- utilizar la clase well -->
<!-- each para todas las tareas y mostrar cada elemento con well -->

<%= link_to "agregar nueva tarea", todos_new_path, class: 'btn btn-success float-right' %>

<h1>ToDo</h1>

<%= link_to "lista", todo_list_path, class: 'btn btn-success' %>

<% @todos.each do |task| %>
 <div class="card card-body bg-light">
   <%= task.description %>
   <%= link_to 'ver', task, class: 'btn btn-success float-left'%>
   <%= link_to 'editar', todo_edit_path(task), class: 'btn btn-primary'%>
   <%= link_to 'eliminar', task, method: :delete, class: 'btn btn-danger'%>
 </div>

 <br>

 <div>
   <% if task.completed == true %>
   <label >realizada</label>
   <% else %>
   <label >pendiente</label>
   <%= link_to 'realizada', todo_completed_path(task), class: 'btn btn-danger' %>
   <% end %>

 </div>
<% end %>

app/views/todos/list.html.erb
<%= render 'layouts/navbar' %>

<%= link_to "volver", todos_path, class: 'btn btn-success float-right' %>

<h1>Listado</h1>
<div class="row">
  <div class="col-6">
    <h4>incompletos</h4>
    <% @todos.each do |task| %>
      <% if task.completed != true %>
        <li><%= task.description %></li>
      <% end %>
    <% end %>

    </div>

    <div class="col-6"><h4>completos</h4>
      <% @todos.each do |task| %>
        <% if task.completed == true %>
          <li><%= task.description %></li>
        <% end %>
      <% end %>

    </div>
</div>

app/views/todos/new.html.erb
<%= render 'layouts/navbar' %>

<!-- boton para volver -->
<%= link_to "volver", todos_path, class: 'btn btn-success float-right' %>

<h1>Nuevo ToDo</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<%= render 'layouts/navbar' %>

<%=link_to "volver", todos_path, class: 'btn btn-success float-right'%>
<h1>Tarea </h1>
<%= @todo.description %>